      SUBROUTINE STORE(ISTR,CRD,NC,IZP,NAT,MM,NN,NND,NM,VEC,IW,NE,EE,NP)

      INTEGER*2 IZP(NAT),MM(NND,NM),NN(NND,NM),IW(2,NE)

      DIMENSION CRD(NC,NAT),VEC(3,NE),EE(NP,NP,NE)

      IF(ISTR.EQ.0)RETURN

      IO=-ISTR

      IF(ISTR.GT.0)GOTO 71

      READ(IO,1)NNC,NNAT

1    FORMAT(2I5)

      IF(NC-NNC)11,51,31

11    WRITE(6,21)NC,NNC

21    FORMAT(' NC ARGUMENT(',I4,') IS LESS THAN NC INPUT(',I4,')')

      STOP

31    WRITE(6,41)NC,NNC

41    FORMAT(' WARNING NC INPUT (',I4,' NOT EQUAL TO ARGUMENT (',I4,')')

51    IF(NNAT.LE.NAT)GOTO 81

      WRITE(6,61)NAT,NNAT

61    FORMAT(' NAT ARGUMENT(',I4,') LESS THAN NAT INPUT(',I4,')')

      STOP

71    WRITE(ISTR,1)NC,NAT

      NNC=NC

      NNAT=NAT

81    NAT=NNAT

      CALL RS4(ISTR,CRD,NNC*NAT)

      CALL IS2(ISTR,IZP,NAT)

      IF(ISTR.GT.0)GOTO 42

      READ(IO,1)NNM

      IF(NND.GE.NAT)GOTO 22

      WRITE(6,12)NND,NAT

12    FORMAT(' ND ARGUMENT(',I4,') IS LESS THAN NO. OF ATOMS(',I4,')')

      STOP

22    IF(NNM.LE.NM)GOTO 52

      WRITE(6,32)NM,NNM

32    FORMAT(' NM ARGUMENT(',I4,') LESS THAN NM INPUT(',I4,')')

      STOP

42    WRITE(ISTR,1)NM

      NNM=NM

52    NM=NNM

      DO 62 I=1,NNM

      CALL IS2(ISTR,MM(1,I),NAT)

62    CALL IS2(ISTR,NN(1,I),NAT)

      IF(NE.EQ.0)RETURN

      IF(ISTR.GT.0)GOTO 43

      READ(IO,1)NNP,NNE

      IF(NNP.EQ.NP)GOTO 23

      WRITE(6,13)NP,NNP

13    FORMAT(' NP ARGUMENT(',I4,') IS NOT EQUAL TO NP INPUT(',I4,')')

      STOP

23    IF(NNE.LE.NE)GOTO 53

      WRITE(6,33)NE,NNE

33    FORMAT(' NE ARGUMENT(',I4,') LESS THAN NE INPUT(',I4,')')

      STOP

43    WRITE(ISTR,1)NP,NE

      NNE=NE

53    NE=NNE

      CALL RS4(ISTR,EE,NP*NP*NNE)

      CALL IS2(ISTR,IW,2*NNE)

      CALL RS4(ISTR,VEC,3*NNE)

      RETURN

      END
