      PROGRAM EXPEELED

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION A(30,3),B2(30,3),WK(30,4),IWK(30,2),HEAD(6),E(201)

     1,EN(201,10),NL(2)

      NPTS=17

      ND=30

      ELO=-0.2

      EHI=0.6

      EPS=5.0E-12

      LL=7

C

C  NPTS IS THE NUMBER OF POINTS TO BE USED IN PLOTTING

C  ELO-EHI IS THE RANGE OF ENERGIES OF INTEREST,

C  EPS IS THE ACCURACY REQUIRED

C  LL IS THE LENGTH OF THE C.F.

C

C  INPUT THE RESULTS OF THE ORPEEL EXAMPLE PROGRAM

C

C

C  LLIN  LENGTH OF C.F.S ON INPUT

C  NPOS  NUMBER OF SETS OF C.F.S

C  NORP  NUMBER OF C.F.S IN EACH SET

C

      READ(5,1)LLIN

1     FORMAT(48X,I3)

      LL=MIN0(LL,LLIN)

      WRITE(6,2)LL

2     FORMAT(' EXAMPLE OF ENERGY CALCULATION IN ORBITAL PEELING',/I4,

     1' LEVELS USED')

      READ(5,3)HEAD,NPOS,NORP

3     FORMAT(22X,6A4,/I4,9X,I3)

      WRITE(6,32)HEAD,NPOS,NORP

32    FORMAT(1X,6A4,I4,' SETS OF',I4,' ORBITALS EACH')

C

C  TABULATE VALUES OF FERMI ENERGY REQUIRED

C

      DE=(EHI-ELO)/FLOAT(NPTS-1)

      DO 34 I=1,NPTS

34    E(I)=ELO+FLOAT(I-1)*DE

C

C  COMPUTE TOTAL ENERGY DIFFERENCE FOR EACH SET OF COEFFICIENTS

C

      DO 10 IPOS=1,NPOS

      READ(5,35)(HEAD(I),I=1,4),(WK(1,K),K=1,3)

35    FORMAT(2X,4A4,3E13.5)

      WRITE(6,36)(HEAD(I),I=1,4),(WK(1,K),K=1,3)

36    FORMAT(///2X,4A4,3F6.2)

      DO 6 I=1,NORP

      READ(5,1)

      READ(5,4)(A(J,I),B2(J,I),J=1,LLIN)

4     FORMAT(2E14.6)

5     FORMAT(' INPUT CONTINUED FRACTION CFTS.',50(/1X,6E11.4))

6     CONTINUE

      WRITE(6,5)((A(I,J),B2(I,J),J=1,NORP),I=1,LL)

C

C   COMPUTE THE TOTAL ENERGY DIFFERENCE  AT EACH VALUE OF

C   THE FERMI ENERGY AND STORE THE RESULT IN EN

C

      DO 9 I=1,NPTS

      EN(I,IPOS)=0.0

      DO 8 K=1,NORP

8     EN(I,IPOS)=EN(I,IPOS)+EDIFF(E(I),A(1,K),B2(1,K),LL,EPS,WK,IWK)

9     CONTINUE

10    CONTINUE

      WRITE(6,105)(I,I=1,NPOS)

105   FORMAT(////' TOTAL ENERGY DIFFERENCES TABULATED AGAINST FERMI ENER

     1GY',/7X,'EF',9(5X,I3,' POSN'))

      DO 11 I=1,NPTS

      WRITE(6,12)E(I),(EN(I,J),J=1,NPOS)

11    CONTINUE

12    FORMAT(10E13.5)

      STOP

      END


