      PROGRAM EXPHNPLT

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION A(100,18),B2(100,18),AA(100),BB2(100),WK(100,18,5)

     1,TABS(511,3),IWK(100),TITL(6),NAT(6),W1(100),W2(100),W3(100)

      NDIM=100

      IO=6

      NPTS=21

      WLO=0.0

      WHI=1.5

      ALP=0.5

      EPS=5.0E-8

      READ(5,11)TITL

11    FORMAT(6A4)

      WRITE(IO,10)TITL

10     FORMAT(10X,6A4)

      READ(5,12)LL,NS

12    FORMAT(I4,10X,I4)

      NP=NS*3

C

C  NDIM IS FIRST DIMENSION OF ARRAYS A AND B2

C  NPTS IS NUMBER OF POINTS OF TABULATION

C  WLO-WHI IS THE RANGE OF FREQUENCIES OF INTEREST,

C  EPS IS THE ACCURACY REQUIRED

C  TITL HOLDS THE TITLE TO BE COPIED FROM INPUT TO OUTPUT

C  LL IS THE LENGTH OF THE CONTINUED FRACTIONS

C  NS IS THE NUMBER OF ATOMS AT WHICH THE PHONON LDOS IS CALCULATED

C  NP (=3*NS) IS THUS THE NUMBER OF SETS OF CONTINUED FRACTION CFTS

C

C  READ IN COEFFICIENTS

C

      DO 1 I=1,NP

      II=(I-1)/3+1

      READ(5,14)NAT(II),IC

14    FORMAT(5X,I5,11X,I2)

      READ(5,2)(A(J,I),B2(J,I),J=1,LL)

1    CONTINUE

2    FORMAT(2E20.12)

      WRITE(IO,13)LL,NS

13    FORMAT(10X,I4,' LEVELS AT',I4,' SITES')

      WRITE(IO,23)(NAT(I),I=1,NS)

23    FORMAT(10X,' ATOMS',10I5)

      DO 4 JJ=1,NP,3

      JM=MIN0(JJ+2,NP)

      WRITE(IO,3)((A(I,J),B2(I,J),J=JJ,JM),I=1,LL)

3    FORMAT(10X,' INPUT CONTINUED FRACTION CFTS.',50(/10X,6E11.4))

4     CONTINUE

C

C  COMPUTE THE SUM OF THE INPUT DENSITIES AND STORE THE RESULTING

C  COEFFICIENTS IN AA AND BB2

C

      CALL RECSUM(A,B2,NDIM,LL,NP,AA,BB2,EPS,WK,5*LL*NP)

      WRITE(IO,2)

      WRITE(IO,22)

22   FORMAT(10X,' RESULTANT CONTINUED FRACTION COEFFICIENTS')

      WRITE(IO,24)(AA(J),BB2(J),J=1,LL)

24    FORMAT(10X,2E20.12)

      DX=(WHI-WLO)/FLOAT(NPTS-1)

      WRITE(IO,2)

C

C  TABULATE PHONON LDOS GIVEN BY 2*W*N(W*W)

C  WHERE N(E) CORRESPONDS TO AN ELECTRON LDOS

C  TABS(I,1) CONTAINS W

C  TABS(I,2) CONTAINS THE PHONON LOCAL DENSITY OF STATES

C  TABS(I,3) CONTAINS THE INTEGRAL OF THE ABOVE

C

      WRITE(IO,5)

5    FORMAT(18X,' OMEGA',5X,' DENSITY OF PHONON MODES INTEGRATED ',

     1'D.O.S.')

      DO 15 I=1,NPTS

      TABS(I,1)=WLO+FLOAT(I-1)*DX

      E=TABS(I,1)*TABS(I,1)

      TABS(I,2)=2.0*TABS(I,1)*DENQD(E,E,AA,BB2,LL,ALP,EPS,WK,NDIM,

     1 NQ,NE,IWK)

      IF(NE.GT.0)GOTO 42

      WRITE(IO,41)WK(I,1,1),NE,I

41    FORMAT(' TROUBLE AT E=',' NQ=',I3,' I=',I3)

      STOP

42    TABS(I,3)=WK(NE,2,1)*(ALP-1.0)

      DO 43 J=1,NE

43    TABS(I,3)=TABS(I,3)+WK(J,2,1)

      TABS(I,3)=TABS(I,3)*2.0

      WRITE(IO,6)(TABS(I,J),J=1,3)

15    CONTINUE

6    FORMAT(10X,3E20.8)

      STOP

      END


